### ISSUE TITLE
_hasher is not defined in AuthenticationController.cs

### ISSUE THREAD

**Issue by JHorvath-MaxetaTech** [jmw5598/dotnet-core-jwt-authentication#2]
![image](https://github.com/jmw5598/dotnet-core-jwt-authentication/assets/28117424/e408f276-0f06-4058-97a8-daef425c4c4a)

**Comment by jmw5598** [comment]
@JHorvath-MaxetaTech This is an old repo from when I was messing around with .NET.  I just pushed up a commit that injects the PasswordHasher which should fix this (didn't actually test but should work), just pull the latest master.
